import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const source = await fs.readFile(new URL('../static/js/viewer/text_mobile_insets.js', import.meta.url), 'utf8');
const { applyMobileTextInsets } = await import('data:text/javascript;base64,' + Buffer.from(source).toString('base64'));
globalThis.window = { innerWidth: 390 };
const header = { offsetHeight: 48 }, footer = { offsetHeight: 58 };
globalThis.document = { getElementById: () => ({ querySelector: s => s.endsWith('-top') ? header : footer }) };
let safeArea = 0;
globalThis.getComputedStyle = () => ({ bottom: `${safeArea}px` });
const wrapper = { style: {} }, content = { style: {} };
const settings = new Map(); const storage = { getItem: k => settings.get(k) ?? null };
applyMobileTextInsets(wrapper, content, storage);
assert.equal(wrapper.style.marginTop, '48px');
assert.equal(wrapper.style.marginBottom, '60px');
assert.equal(wrapper.style.height, 'calc(100% - 108px)');
safeArea = 34; applyMobileTextInsets(wrapper, content, storage);
assert.equal(wrapper.style.marginBottom, '92px');
header.offsetHeight = 56; applyMobileTextInsets(wrapper, content, storage);
assert.equal(wrapper.style.marginTop, '56px');
settings.set('viewer_padding_top', '100'); applyMobileTextInsets(wrapper, content, storage);
assert.equal(wrapper.style.marginTop, '100px');
window.innerWidth = 1100; const before = {...wrapper.style};
assert.equal(applyMobileTextInsets(wrapper, content, storage), false);
assert.deepEqual(wrapper.style, before);
console.log('PASS mobile toolbar insets, safe area, explicit padding, desktop unchanged');
